{
  pkgs,
  fancy,
  ...
}: let
  inherit (pkgs) lib;
  inherit
    (lib)
    types
    ;
  inherit
    (fancy)
    w-k-x
    err
    ;

  _modules = rec {
    mod-eval = modules: special-args: extra-opts:
      lib.evalModules ({
          specialArgs = special-args;
          inherit modules;
        }
        // extra-opts);
    mod-bake = module-args: bake-args: let
      # allow string or lists in path and auto-handle them
      namespace =
        bake-args.ns or (
          err.required-k "ns" "Use `mod-ns` for setting the namespace!"
        );
      _namespace = let
        t = fancy.type-of namespace;
      in
        if t == "list"
        then namespace
        else if t == "string"
        then [namespace]
        else err.unexpected-t' t "string or list";
      _get-namespace = _attrsets.get-path _namespace;
      _set-namespace = _attrsets.set-path _namespace;
      _lambda-args = {
        cfg = module-args.config |> _get-namespace;
      };
      # recurse to resolve:
      # - lambdas, by applying `lambda-args`
      # - lists, by applying `merge` (if `lists-ok` is true)
      #
      # `x` is reduced into attrset
      _handle-arg = lists-ok: x: let
        t = fancy.type-of x;
      in
        if t == "set"
        then x
        else if t == "lambda"
        then _handle-arg lists-ok (x _lambda-args)
        else if t == "list" && lists-ok
        then merge (map (_handle-arg lists-ok) x)
        else
          err.unexpected-t' t (
            if lists-ok
            then "lambda, list, or attrset"
            else "lambda or attrset"
          );

      options = bake-args.opts or {} |> _handle-arg false |> _set-namespace;
      config = bake-args.cfg or {} |> _handle-arg true;
      imports = bake-args.imports or [];
      extra = bake-args.extra or {} |> _handle-arg false;
    in
      extra # we reject deep merges to avoid spooky behavior
      // {
        inherit
          options
          config
          imports
          ;
      };
    mod-ns = ns: {inherit ns;};
    w-opts = w-k-x "opts";
    w-cfg = w-k-x "cfg";
    w-extra = w-k-x "extra";
    w-imports = w-k-x "imports";
    w-freeform = w-k-x "freeformType";

    when = lib.mkIf;
    merge = lib.mkMerge;
    force = lib.mkForce;
    override = lib.mkOverride;
    default = lib.mkDefault;
    do-at = lib.mkOrder;
    do-before = lib.mkBefore;
    do-after = lib.mkAfter;
    do-assert = lib.mkAssert;
    opt = t: lib.mkOption {type = t;};

    # these become functions that take an existing option
    # definition and update it to include a new field
    w-def = w-k-x "default";
    w-def-txt = w-k-x "defaultText";
    w-desc = w-k-x "description";
    w-example = w-k-x "example";
    w-apply = w-k-x "apply";
    # these we can already mark the next arg since they curry
    w-internal = w-k-x "internal" true;
    w-hidden = w-k-x "visible" false;
    w-read-only = w-k-x "readOnly" true;
  };

  _types = {
    inherit
      (types)
      port
      str
      float
      number
      int
      bool
      anything
      unspecified
      raw
      lines
      package
      enum
      ;

    json-format = pkgs.formats.json {};

    bool-or = types.boolByOr;
    path-store = types.pathInStore;
    path-external = types.externalPath;
    path-relative = types.pathWith {absolute = false;};
    path-absolute = types.pathWith {absolute = true;};

    # "modifiers"
    list = types.listOf;
    attrs = types.attrsOf;
    attrs-any = types.attrs;
    attrs-lazy = types.lazyAttrsOf;
    or-null = types.nullOr;
    or-either = types.either;
    one-of = types.oneOf;

    # other
    mod-sub = types.submodule;
    mod-deferred = types.deferredModule;
  };

  _attrsets = {
    get-path = lib.getAttrFromPath;
    set-path = lib.setAttrByPath;
    deep-merge = lib.attrsets.recursiveUpdate;
    when-attrs = lib.optionalAttrs;
    map-attrs = lib.mapAttrs;
    attr-values = lib.attrValues;
  };

  _lists = {
    sort-by = lib.sortOn;
    dedupe = lib.unique;
    when-list = lib.optionals;
    inherit (lib) flatten;
  };

  _meta = {
    default-prio = lib.meta.defaultPriority;
  };

  _strings = {
    str-from-bool = lib.boolToString;
    when-str = lib.optionalString;
    merge-lines = lib.concatLines;
    split-str = lib.splitString;
    escape-shell-str = lib.escapeShellArg;
    to-shell-var = lib.toShellVar;
    inherit (lib) join;
  };

  _drv = rec {
    _run-yj = {
      filename,
      input-content,
      yj-args,
      # header comments
      header ? {
        enable = true;
        text = ''
          DO NOT MODIFY!!!
          This file was auto-generated by Nix.
        '';
        chars-start = "# ";
        chars-end = "";
      },
      extra ? {
        build-inputs = [];
        pass-as-file = [];
        args = {};
      },
      ...
    }: let
      _mk_comment_line = chars-start: chars-end: line-text: (
        chars-start + line-text + chars-end
      );
      _header_echo =
        header.text
        |> _strings.split-str "\n"
        |> map (_mk_comment_line header.chars-start header.chars-end)
        |> map (x: "echo " + (x |> _strings.escape-shell-str) + ";")
        |> _strings.merge-lines;

      _run-args =
        _attrsets.deep-merge
        (extra.args or {})
        {
          inherit filename;
          build-inputs = [pkgs.yj] ++ (extra.build-inputs or []);
          args.rawInput = builtins.toJSON input-content;
          pass-as-file = ["rawInput"] ++ (extra.pass-as-file or []);
          text =
            # bash
            ''
              {
                ${_header_echo}
                yj ${yj-args} < $rawInputPath;
              } > $out
            '';
        };
    in
      run-cmd _run-args;
    write-toml = {
      filename,
      input-content,
      yj-args ? "-jt",
      args ? {},
    }:
      _run-yj (_attrsets.deep-merge args {
        inherit
          filename
          input-content
          yj-args
          ;
      });
    run-cmd = {
      filename,
      text,
      build-inputs ? [],
      native-build-inputs ? [],
      pass-as-file ? [],
      args ? {},
    }:
      pkgs.runCommand
      filename
      ({
          nativeBuildInputs = native-build-inputs;
          buildInputs = build-inputs;
          passAsFile = pass-as-file;
        }
        // args)
      text;

    _shell = pkgs.runtimeShell;

    mk-shell-script = {
      name,
      text,
      bin ? true,
      runtime-deps ? [],
      runtime-envvars ? {},
      bash-options ? ["errexit" "nounset" "pipefail"],
      check-phase ? "",
      allow-substitution ? true,
      prefer-local-build ? false,
      inherit-path ? true,
    }:
      pkgs.writeTextFile ({
          inherit name;
          executable = true;
          allowSubstitutes = allow-substitution;
          preferLocalBuild = prefer-local-build;
          text =
            [
              "#!${_shell}"
              (bash-options
                |> map (opt: "set -o ${opt}")
                |> _strings.merge-lines)
              (_strings.when-str (runtime-envvars != {})
                <| _strings.merge-lines
                <| _attrsets.attr-values
                <| _attrsets.map-attrs (
                  k: v: ''
                    ${_strings.to-shell-var k v}
                    export ${k}
                  ''
                )
                <| runtime-envvars)
              # bash
              ''
                export PATH="${
                  _lists.when-list (runtime-deps != []) [(mk-bin-path runtime-deps)]
                  ++ _lists.when-list inherit-path ["$PATH"]
                  |> _strings.join ":"
                }"

                ${text}
              ''
            ]
            |> fancy.filter (x: x != "")
            |> _strings.merge-lines;
          checkPhase =
            # bash
            ''
              runHook preCheck
              ${pkgs.stdenv.shellDryRun} "$target"
              ${check-phase}
              runHook postCheck
            '';
        }
        // _attrsets.when-attrs bin {
          destination = "/bin/${name}";
          meta.mainProgram = name;
        });

    mk-search-path = lib.makeSearchPath;
    mk-bin-path = lib.makeBinPath;
    get-exe = lib.getExe;
    get-exe' = lib.getExe';
  };

  # helpers (built ontop the other helpers, 2nd order helpers?)
  _helpers = rec {
    _w-toggle = _types.bool |> _modules.opt;
    w-toggle = _w-toggle |> _modules.w-def true;
    w-toggle' = _w-toggle |> _modules.w-def false;
  };
in
  _modules
  // _types
  // _attrsets
  // _lists
  // _meta
  // _strings
  // _helpers
  // _drv
