{
  pkgs,
  fancy,
  ...
} @ args: let
  inherit
    (fancy)
    # keep-sorted start
    attr-values
    attrs
    attrs-any
    do-at
    enum
    env-or
    err
    escape-shell-str
    filter
    get-exe
    lines
    list
    map-attrs
    merge-lines
    mk-shell-script
    mod-bake
    mod-ns
    mod-sub
    opt
    or-null
    package
    raw
    read-file
    str
    str-from-bool
    type-of
    w-cfg
    w-def
    w-desc
    w-opts
    w-toggle
    w-toggle'
    when-attrs
    write-json
    write-toml
    write-yaml
    # keep-sorted end
    ;

  file-types = [
    "json"
    "json-c"
    "toml"
    "yaml"
    # "text" # TODO: later
    # "text-c"
  ];

  file-type-writers = {
    json = write-json;
    jsonc = write-json;
    toml = write-toml;
    yaml = write-yaml;
  };
  file-mod = mod-sub {
    options = {
      type =
        file-types
        |> enum
        |> opt
        |> w-desc "Type of file for being written";
      data =
        attrs-any
        |> opt
        |> w-desc "File data to write";
      force =
        w-toggle
        |> w-desc "If set, will overwrite existing files in the location.";
      header-comments = {
        enable =
          w-toggle
          |> w-desc ''
            If set, will add auto-generated comments at the top of the file,
            which are useful to warn against trying to modify such files.

            Regardless of file type, header comments won't be added for files
            of types: 'json'. If you want comments in these too, use
            their 'c' variants: 'json-c'.
          '';
      };
    };
  };
in
  mod-bake args (
    mod-ns []
    |> w-opts {
      file =
        file-mod
        |> attrs
        |> opt
        |> w-def {}
        |> w-desc ''
          Files to write from the repository root.

          Path names are derived from the attrset keys.
        '';
    }
    |> w-cfg ({cfg, ...}: let
      _installer =
        get-exe
        <| mk-shell-script {
          name = "file_installer";
          text = read-file ./file-installer.sh;
          runtime-deps = [pkgs.git];
        };
      handle-file = k: v: let
        writer =
          file-type-writers.${
            v.type
          } or (err.required-k "type" ''
            Unexpected file type '${v.type}'
          '');
        source-path = writer ({
            filename = "nix_vessel_autogenerated.${v.type}";
            input-content = v.data;
          }
          // when-attrs (v.type == "json-c") {
            header-ok = true;
          }
          // when-attrs (v.header-comments.enable == false) {
            args.header.enable = false;
          });

        _source-esc = escape-shell-str source-path;
        _target-esc = escape-shell-str k;
        _force-esc = escape-shell-str <| str-from-bool v.force;
      in
        # bash
        "${_installer} ${_source-esc} ${_target-esc} ${_force-esc}";
    in {
      shell-hook =
        cfg.file
        |> map-attrs handle-file
        |> attr-values
        |> merge-lines
        |> do-at 15;
    })
  )
